stages:
  - test
  - build

default:
  tags:
    - shell
  cache:
    - key:
        files:
          - poetry.lock
      paths:
        - .venv
  before_script:
    - python3.8 -m venv .venv
    - source .venv/bin/activate
    - pip install --upgrade pip
    - pip install poetry
    - poetry config virtualenvs.in-project true
    - poetry install --no-root --no-interaction --with=dev


tests:
  stage: test
  script:
    - pytest -v --color=no --junit-xml=results.xml --cov-report=html:htmlcov
  coverage: '/TOTAL\s+(?:\d+\s+){4}(\d+\.?\d+)%/'
  artifacts:
    when: always
    name: tvl_coverage
    paths:
      - htmlcov
    expose_as: tests coverage report
    reports:
      junit: results.xml


package:
  stage: build
  needs: []
  script:
    - poetry build --format=wheel
  artifacts:
    paths:
      - dist/
